### ISSUE TITLE
Multithreading_demo does not work when there are ints on the word list.

### ISSUE THREAD

**Issue by cardweller** [ppongpeauk/va-dmv-plate-checker#1]
Demo works well when an int is given, But if the word list has only ints, nothing happens. For Example, a word list of:

4234
92
845  

will not work in multihreading_demo.

**Comment by ppongpeauk** [comment]
After doing some testing, number-only plates never seem to be available, at least according to the website.

Outside of the scope of what was mentioned here, though, the DMV seems to have updated their website a bit which broke the library. I've fixed it in the latest commit 236f3ba and changed how things are returned. I've provided some examples in README.md.
